# Generated by Django 3.2.21 on 2023-09-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
