# Generated by Django 3.2.21 on 2023-10-03 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='foreign_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.catgoryproduct'),
            preserve_default=False,
        ),
    ]
