# Generated by Django 3.2.21 on 2023-10-17 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_for_basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_for_basket', to='products.product')),
                ('user_for_basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_for_basket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
