# Generated by Django 3.2.21 on 2023-10-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_basket_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='total_price',
        ),
    ]
