# Generated by Django 3.2.21 on 2023-10-19 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_basket_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveriInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('numder_of_house', models.IntegerField()),
                ('phone', models.CharField(max_length=30)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='products.basket')),
            ],
            options={
                'verbose_name': 'Информация о доставке',
                'verbose_name_plural': 'Информация о доставках',
            },
        ),
    ]
