# Generated by Django 3.2.21 on 2023-10-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_deliveriinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveriinformation',
            name='basket_information',
            field=models.TextField(default='Ничего нет'),
        ),
    ]
