# Generated by Django 3.2.21 on 2023-10-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_deliveriinformation_basket_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveriinformation',
            name='numder_of_house',
            field=models.CharField(max_length=30),
        ),
    ]
