# Generated by Django 3.2.21 on 2023-10-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_deliveriinformation_numder_of_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveriinformation',
            name='choose_payment_method',
            field=models.CharField(choices=[('П', 'Оплата при получении'), ('К', 'Оплата на карту')], default='Ничего не выбрано', max_length=1),
        ),
    ]
